# Temporary configuration of n4o-graph-apis for docker compose 
---
sparql:
  endpoint: "http://fuseki:3030/n4o"
  # TODO: this path is inside the container!
  examples:
    - queries/*.rq

# this must be a mounted docker volume
stage: ./stage

# Link to tools
tools:
  - name: LIDO-Schulung
    url: https://docs.nfdi4culture.de/lido-schulung
    description: Einführung in das LIDO-Format
